// This file has been generated by Specta. DO NOT EDIT.

export type AudioGenerationResult = { id: string; chat_id: string; relpath: string }

export type AiChatEntry = { id: string; chat_id: string; relpath: string; error: string }

export type ChatEntry = { User: UserChatEntry } | { Ai: AiChatEntry }

export type UserChatEntry = { id: string; chat_id: string; text: string }

export type InboundMsg = { GenerateAudio: GenerateAudio } | { AbortGeneration: AbortGeneration } | { RetrieveHistory: RetrieveHistory }

export type RetrieveHistory = { chat_id: string }

export type AudioGenerationStart = { id: string; chat_id: string }

export type AudioGenerationProgress = { id: string; chat_id: string; progress: number }

export type AbortGeneration = { id: string; chat_id: string }

export type OutboundMsg = { Generation: GenerationMessage } | { Init: Info } | { ChatHistory: [string, ChatEntry[]] }

export type Info = { model: string; device: string }

export type GenerateAudio = { id: string; chat_id: string; prompt: string; secs: number }

export type GenerationMessage = { Start: AudioGenerationStart } | { Progress: AudioGenerationProgress } | { Error: AudioGenerationError } | { Result: AudioGenerationResult }

export type AudioGenerationError = { id: string; chat_id: string; error: string }

