// This file has been generated by Specta. DO NOT EDIT.

export type BackendAiInboundMsg = { AudioGenerationRequest: AudioGenerationRequest } | { Abort: string } | "TearDown"

export type AudioGenerationRequest = { id: string; prompt: string; secs: number }

export type BackendAiOutboundMsg = { AudioGenerationResponse: [string, string] } | { AudioGenerationFailure: [string, string] } | { AudioGenerationProgress: [string, number] }

