// This file has been generated by Specta. DO NOT EDIT.

export type Init = { model: string; device: string }

export type OutboundMsg = { Progress: AudioGenerationProgress } | { Error: AudioGenerationError } | { Result: AudioGenerationResult } | { Init: Init } | { History: [string, HistoryEntry[]] }

export type HistoryEntry = { User: UserHistoryEntry } | { Ai: AiHistoryEntry }

export type UserHistoryEntry = { id: string; chat_id: string; text: string }

export type AiHistoryEntry = { id: string; chat_id: string; relpath: string }

export type AbortGeneration = { id: string; chat_id: string }

export type InboundMsg = { GenerateAudio: GenerateAudio } | { AbortGeneration: AbortGeneration } | { RetrieveHistory: RetrieveHistory }

export type AudioGenerationResult = { id: string; chat_id: string; relpath: string }

export type AudioGenerationError = { id: string; chat_id: string; error: string }

export type GenerateAudio = { id: string; chat_id: string; prompt: string; secs: number }

export type AudioGenerationProgress = { id: string; chat_id: string; progress: number }

export type RetrieveHistory = { chat_id: string }

